export const ENV = {
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
    FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
    TOKEN: process.env.TOKEN,
    MERCADO_PAGO_PUBLIC_KEY: process.env.MERCADO_PAGO_PUBLIC_KEY,
    MERCADO_PAGO_ACCESS_TOKEN: process.env.MERCADO_PAGO_ACCESS_TOKEN,
    MERCADO_PAGO_PUBLIC_KEY_NORMAL: process.env.MERCADO_PAGO_PUBLIC_KEY_NORMAL,
    MERCADO_PAGO_ACCESS_TOKEN_NORMAL: process.env.MERCADO_PAGO_ACCESS_TOKEN_NORMAL,
    MERCADO_PAGO_CLIENT_ID: process.env.MERCADO_PAGO_CLIENT_ID,
    MERCADO_PAGO_CLIENT_SECRET: process.env.MERCADO_PAGO_CLIENT_SECRET,
    MERCADO_PAGO_REDIRECT_URI: process.env.MERCADO_PAGO_REDIRECT_URI,
    APP_ID: process.env.APP_ID,
    MERCADO_PAGO_APLICATION_FEE_PERCENTAJE: process.env.MERCADO_PAGO_APLICATION_FEE_PERCENTAJE,
    URL_FRONT: process.env.URL_FRONT,
    URL_API: process.env.URL_API

}
